### ISSUE TITLE
$Function 功能太少了，大佬给否完善一下？

### ISSUE THREAD

**Issue by atjiu** [kevin-wang001/mockj#4]
比如常用的 `@name` `@address` `@email`

**Comment by kevin-wang001** [comment]
可以 fork 之后，自己加的。
现在项目已经发到 maven 中央仓库了，可以直接引用了。https://gitee.com/kkk001/mockj

**Comment by kevin-wang001** [comment]
后续考虑在这个地方预留扩展点
